### ISSUE TITLE
GetDate extension method fails to cater for all faulty data returned by the API

### ISSUE THREAD

**Issue by daleholborow** [EodHistoricalData/EODHistoricalData.Wrapper#11]
Specifically, the API returns not only garbage dates like "0000-00-00" but also other rubbish like "0000-03-31". I notice this in particular, when downloading exchange symbol (fundamental) data from exchange code "F",  earnings trends in particular. This crashes deserialization with exceptions like that pasted at bottom.

The date cleansing method recently put in place is overly specific and only handles one type of rubbish value, using the TryParse method would probably be more suitable and handle the full range of bad date data, (if the data itself cannot be fixed, which is obviously preferable).

```
internal static DateTime? ParseDate(string dateStr)
        {
            if (dateStr == "0000-00-00")  // THIS IS TOO SPECIFIC AND DOESNT HANDLE exceptions like that pasted below
            {
                return null;
            }
            else
            {
                return DateTime.Parse(dateStr);
            }
        }
```

```
Newtonsoft.Json.JsonSerializationException: Error converting value "0000-03-31" to type 'System.DateTime'. Path 'Earnings.Trend.0000-03-31', line 1, position 8574.
 ---> System.FormatException: String '0000-03-31' was not recognized as a valid DateTime.
   at System.Convert.ToDateTime(String value, IFormatProvider provider)
   at System.String.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
```

**Comment by daleholborow** [comment]
![image](https://user-images.githubusercontent.com/9979412/191846563-cebf84cb-aa16-4b9c-bf07-48c9b21e6b26.png)

https://eodhistoricaldata.com/api/fundamentals/BNT1.F?api_token={yourtokenhere}

**Comment by daleholborow** [comment]
Another point (sorry for breaking these up, I add comments as I discover additional cases), the earnings trend figures are stored in a Dictionary<datetime, > so cannot be simply string replaced from 0000-00 and 0000-03 to null, because the dictionary cannot have null as a key. The data needs to be fixed or excluded during parsing by a custom parser maybe?

**Comment by daleholborow** [comment]
ParseDate(string dateStr) <- cannot be null either, or blows up properties like the BalanceSheet.FilingDate property (e.g. Stock EQV1V.HE fundamentals query, accessing yearly filing date values throws exceptions)

**Comment by daleholborow** [comment]
@nicethatcher  is there an ETA for this push to nuget?

**Comment by nicethatcher** [comment]
@daleholborow the package has been updated, thank you for your patience.
